apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: block-north-korea
spec:
  ruleId: 1001
  phase: 2
  action: deny
  enabled: true
  httpStatus: 403
  ruleLogic:
    type: MATCH
    operator: "@geoLookup"
    variables:
      - type: IP
    match: "KP"
    metadata:
      message: "Blocked traffic from North Korea"
      severity: "CRITICAL"
      tags: ["geo"]
---
apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: block-specific-ip
spec:
  ruleId: 1002
  phase: 1
  action: deny
  enabled: true
  ruleLogic:
    type: MATCH
    operator: "@ipMatch"
    variables:
      - type: IP
    match: "192.168.100.1"
    metadata:
      message: "Blocked specific IP"
      severity: "HIGH"
      tags: ["ip"]
---
apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: block-admin-uri
spec:
  ruleId: 1003
  phase: 2
  action: deny
  enabled: true
  ruleLogic:
    type: MATCH
    operator: "@contains"
    variables:
      - type: REQUEST_URI
    match: "admin"
    metadata:
      message: "Blocked /admin in URI"
      severity: "MEDIUM"
      tags: ["uri"]
---
apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: block-get-method
spec:
  ruleId: 1004
  phase: 2
  action: deny
  enabled: true
  ruleLogic:
    type: MATCH
    operator: "@streq"
    variables:
      - type: REQUEST_METHOD
    match: "GET"
    metadata:
      message: "Blocked GET method"
      severity: "LOW"
      tags: ["method"]
---
apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: block-sql-injection
spec:
  ruleId: 1005
  phase: 2
  action: deny
  enabled: true
  ruleLogic:
    type: MATCH
    operator: "@rx"
    variables:
      - type: REQUEST_BODY
    match: "(?i)(union select|drop table|insert into)"
    transformations: ["urlDecode", "lowercase"]
    metadata:
      message: "SQL Injection detected"
      severity: "CRITICAL"
      tags: ["sqli"]
---
apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: block-xss
spec:
  ruleId: 1006
  phase: 2
  action: deny
  enabled: true
  ruleLogic:
    type: MATCH
    operator: "@rx"
    variables:
      - type: REQUEST_BODY
    match: "<script.*?>"
    transformations: ["htmlEntityDecode", "lowercase"]
    metadata:
      message: "XSS attack detected"
      severity: "CRITICAL"
      tags: ["xss"]
---
apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: block-user-agent-bot
spec:
  ruleId: 1007
  phase: 1
  action: deny
  enabled: true
  ruleLogic:
    type: MATCH
    operator: "@rx"
    variables:
      - type: REQUEST_HEADERS
        selector: "User-Agent"
    match: "(curl|wget|nikto)"
    metadata:
      message: "Blocked unwanted bots"
      severity: "HIGH"
      tags: ["bot"]
---
apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: block-sensitive-cookie
spec:
  ruleId: 1008
  phase: 2
  action: deny
  enabled: true
  ruleLogic:
    type: MATCH
    operator: "@contains"
    variables:
      - type: REQUEST_COOKIES
        selector: "sessionid"
    match: "admin"
    metadata:
      message: "Blocked session cookie containing admin"
      severity: "HIGH"
      tags: ["cookie"]
---
apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: complex-and-or
spec:
  ruleId: 1009
  phase: 2
  action: deny
  enabled: true
  httpStatus: 403
  ruleLogic:
    type: AND
    children:
      - type: MATCH
        operator: "@geoLookup"
        variables:
          - type: IP
        match: "KP"
        metadata:
          message: "From North Korea"
          severity: "CRITICAL"
      - type: OR
        children:
          - type: MATCH
            operator: "@ipMatch"
            variables:
              - type: IP
            match: "192.168.100.1"
            metadata:
              message: "Bad IP"
              severity: "HIGH"
          - type: MATCH
            operator: "@contains"
            variables:
              - type: REQUEST_URI
            match: "admin"
            metadata:
              message: "Admin URI"
              severity: "HIGH"
