apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: shahram-rule1
  namespace: "1731930192436"
spec:
  order: 2
  cdnGateway: "shahram"
  enabled: true
  description: "Allow traffic only from Iran or Greatest Britain, block all other countries"
  conditions:
    - - param: country
        operator: not_in
        value: IR,GB
  action:
    type: deny
    message: "Access allowed only from Iran or United Kingdom."
    code: 403
