apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: block-admin-access
  namespace: default
spec:
  gateway:
    name: my-gateway
  ruleId: 1001
  phase: 1
  action: deny
  operator: contains
  variables:
    - type: REQUEST_HEADERS
      selector: X-Request-Uri
  match: "admin"
  transformations: ["lowercase", "urlDecode"]
  metadata:
    severity: "critical"
    message: "Blocked admin access attempt"
    tags: ["security", "authentication"]
  enabled: true
  # httpStatus: 403 # Optional - defaults to 403
