apiVersion: cdn.ik8s.ir/v1alpha1
kind: WAFRule
metadata:
  name: rule1
  namespace: "1731930192436"
spec:
  cdnGateway: "gw11"
  enabled: true
  description: "Allow traffic only from Iran, block all other countries"
  conditions:
    - - param: country
        operator: in
        value: IR
  action:
    type: deny
    message: "Access allowed only from Iran"
    code: 403
