apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wafrules.cdn.ik8s.ir
spec:
  group: cdn.ik8s.ir
  names:
    kind: WAFRule
    listKind: WAFRuleList
    plural: wafrules
    singular: wafrule
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [ruleId, phase, action]
              properties:
                gateway:
                  type: object
                  properties:
                    name:
                      type: string
                ruleId:
                  type: integer
                  minimum: 1
                phase:
                  type: integer
                  minimum: 1
                  maximum: 5
                action:
                  type: string
                  enum:
                    [
                      allow,
                      deny,
                      drop,
                      pass,
                      proxy,
                      redirect,
                      chain,
                      log,
                      auditlog,
                      status,
                      capture,
                      t,
                      msg,
                      tag,
                      logdata,
                      severity,
                      multiMatch,
                      ver,
                      rev,
                      id,
                      skip,
                      skipAfter,
                      ctl,
                      initcol,
                      setenv,
                      setvar,
                    ]
                operator:
                  type: string
                  enum:
                    [
                      contains,
                      beginsWith,
                      endsWith,
                      equals,
                      regex,
                      geoLookup,
                      ipMatch,
                      unconditionalMatch,
                      within,
                      detectSQLi,
                      detectXSS,
                      pm,
                      pmFromFile,
                      rx,
                      streq,
                      validateByteRange,
                      validateUrlEncoding,
                      validateUtf8Encoding,
                      verifyCC,
                      verifyCPF,
                      verifyCNPJ,
                      verifySSN,
                    ]
                variables:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      selector:
                        type: string
                      count:
                        type: boolean
                        default: false
                      exclusion:
                        type: boolean
                        default: false
                transformations:
                  type: array
                  items:
                    type: string
                    enum:
                      [
                        none,
                        lowercase,
                        urlDecode,
                        htmlEntityDecode,
                        base64Decode,
                        removeWhitespace,
                        removeNulls,
                        cmdLine,
                        compressWhitespace,
                        base64Encode,
                      ]
                match:
                  type: string
                metadata:
                  type: object
                  properties:
                    severity:
                      type: string
                      enum:
                        [
                          emergency,
                          alert,
                          critical,
                          error,
                          warning,
                          notice,
                          info,
                          debug,
                        ]
                    message:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
                enabled:
                  type: boolean
                  default: true
                httpStatus:
                  type: integer
                  minimum: 100
                  maximum: 599
                # Action-specific fields
                redirect:
                  type: string
                status:
                  type: integer
                setvar:
                  type: object
                  properties:
                    variable: string
                    value: string
                    scope: string
                initcol:
                  type: object
                  properties:
                    collection: string
                    variable: string
                skip:
                  type: integer
                skipAfter:
                  type: string
                # Chain rules with proper structure
                chain:
                  type: boolean
                  default: false
                chainRules:
                  type: array
                  items:
                    type: object
                    required: [operator, match]
                    properties:
                      operator:
                        type: string
                      variables:
                        type: array
                        items:
                          type: object
                          properties:
                            type: string
                            selector: string
                      transformations:
                        type: array
                        items:
                          type: string
                      match:
                        type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type: string
                      status: string
                      lastTransitionTime: string
                      reason: string
                      message: string
                lastAppliedHash: string
                synced: boolean
      served: true
      storage: true
      subresources:
        status: {}
