apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wafrules.cdn.ik8s.ir
spec:
  group: cdn.ik8s.ir
  names:
    kind: WAFRule
    listKind: WAFRuleList
    plural: wafrules
    singular: wafrule
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [ruleId, phase, action]
              properties:
                gateway:
                  type: object
                  properties:
                    name:
                      type: string
                ruleId:
                  type: integer
                  minimum: 1
                  description: Unique numeric ID for the rule (required)
                phase:
                  type: integer
                  minimum: 1
                  maximum: 5
                  description: Phase of request processing (1-5, required)
                action:
                  type: string
                  enum: [allow, deny, drop, pass, proxy, redirect, chain]
                  description: Disruptive action to take (required)
                operator:
                  type: string
                  enum:
                    [
                      contains,
                      beginsWith,
                      endsWith,
                      equals,
                      regex,
                      geoLookup,
                      ipMatch,
                      unconditionalMatch,
                      within,
                      detectSQLi,
                      detectXSS,
                    ]
                  description: Operator for comparison
                variables:
                  type: array
                  items:
                    type: object
                    required: [type]
                    properties:
                      type:
                        type: string
                        description: Variable category (e.g., ARGS, REQUEST_HEADERS, REQUEST_BODY)
                      selector:
                        type: string
                        description: Specific field selector (e.g., "User-Agent", "username")
                transformations:
                  type: array
                  items:
                    type: string
                    enum:
                      [
                        none,
                        lowercase,
                        urlDecode,
                        htmlEntityDecode,
                        base64Decode,
                        removeWhitespace,
                        removeNulls,
                        cmdLine,
                        compressWhitespace,
                        base64Encode,
                      ]
                match:
                  type: string
                  description: Pattern to match against for the operator
                metadata:
                  type: object
                  properties:
                    severity:
                      type: string
                      enum:
                        [
                          emergency,
                          alert,
                          critical,
                          error,
                          warning,
                          notice,
                          info,
                          debug,
                        ]
                    message:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
                enabled:
                  type: boolean
                  default: true
                  description: Whether the rule is active
                httpStatus:
                  type: integer
                  minimum: 100
                  maximum: 599
                  description: Optional HTTP status code for deny actions (defaults to 403)
                chain:
                  type: boolean
                  default: false
                  description: Whether this rule is a chain starter
                chainRules:
                  type: array
                  items:
                    type: object
                    properties:
                      ruleId:
                        type: integer
                        minimum: 1
                      phase:
                        type: integer
                        minimum: 1
                        maximum: 5
                      operator:
                        type: string
                        enum:
                          [
                            contains,
                            beginsWith,
                            endsWith,
                            equals,
                            regex,
                            geoLookup,
                            ipMatch,
                            unconditionalMatch,
                            within,
                            detectSQLi,
                            detectXSS,
                          ]
                      variables:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                            selector:
                              type: string
                      match:
                        type: string
                      transformations:
                        type: array
                        items:
                          type: string
                  description: Rules that are chained to this one (limited subset of fields for chain links)
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                lastAppliedHash:
                  type: string
                synced:
                  type: boolean
      served: true
      storage: true
      subresources:
        status: {}
