apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wafrules.cdn.ik8s.ir
spec:
  group: cdn.ik8s.ir
  names:
    kind: WAFRule
    listKind: WAFRuleList
    plural: wafrules
    singular: wafrule
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gateway:
                  type: object
                  properties:
                    name:
                      type: string
                ruleId:
                  type: integer
                  description: Unique ID for the rule
                phase:
                  type: integer
                  minimum: 1
                  maximum: 5
                  description: Phase of request processing (1-5)
                action:
                  type: string
                  enum:
                    [
                      block,
                      deny,
                      allow,
                      pass,
                      drop,
                      proxy,
                      redirect,
                      log,
                      auditlog,
                    ]
                operator:
                  type: string
                  enum:
                    [
                      contains,
                      regex,
                      eq,
                      ge,
                      le,
                      beginsWith,
                      endsWith,
                      validateByteRange,
                      ipMatch,
                    ]
                variables:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      selector:
                        type: string
                transformations:
                  type: array
                  items:
                    type: string
                    enum: [lowercase, urlDecode, htmlEntityDecode, removeNulls]
                match:
                  type: string
                  description: Pattern to match against
                metadata:
                  type: object
                  properties:
                    severity:
                      type: string
                      enum:
                        [
                          emergency,
                          alert,
                          critical,
                          error,
                          warning,
                          notice,
                          info,
                          debug,
                        ]
                    message:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
                status:
                  type: integer
                  description: HTTP status code for actions
                ttl:
                  type: integer
                  description: Time to live in seconds
      served: true
      storage: true
      subresources:
        status: {}
