apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wafrules.cdn.ik8s.ir
spec:
  group: cdn.ik8s.ir
  names:
    kind: WAFRule
    plural: wafrules
    singular: wafrule
    listKind: WAFRuleList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [cdnGateway, ruleId, phase, action, ruleLogic]
              properties:
                cdnGateway:
                  type: object
                  properties:
                    name:
                      type: string
                ruleId:
                  type: integer
                  minimum: 1
                phase:
                  type: integer
                  minimum: 1
                  maximum: 5
                action:
                  type: string
                  enum:
                    - allow
                    - deny
                    - drop
                    - pass
                    - proxy
                    - redirect
                    - log
                    - auditlog
                    - status
                    - capture
                enabled:
                  type: boolean
                  default: true
                httpStatus:
                  type: integer
                  minimum: 100
                  maximum: 599
                ruleLogic:
                  type: object
                  required: [type]
                  properties:
                    type:
                      type: string
                      enum: ["AND", "OR", "MATCH"]
                    operator:
                      type: string
                    match:
                      type: string
                    variables:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          selector:
                            type: string
                          count:
                            type: boolean
                            default: false
                          exclusion:
                            type: boolean
                            default: false
                          key:
                            type: string
                    transformations:
                      type: array
                      items:
                        type: string
                        enum:
                          [
                            "none",
                            "lowercase",
                            "urlDecode",
                            "htmlEntityDecode",
                            "base64Decode",
                            "removeWhitespace",
                            "removeNulls",
                            "cmdLine",
                            "compressWhitespace",
                            "base64Encode",
                          ]
                    children:
                      type: array
                      items:
                        type: object
                        properties: {} # inline recursion
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                    required: [type, status]
                lastAppliedHash:
                  type: string
                synced:
                  type: boolean
      subresources:
        status: {}
